openapi: 3.0.1
info:
  title: paylink
  description: API Definition of paylink
  version: "1"
servers:
- url: http://localhost:8290/paylink
paths:
  /:
    get:
      responses:
        default:
          description: Default response
